#ifndef	_DEADCAFE_ERR_H_
#define	_DEADCAFE_ERR_H_

/* The following lines are auto generated by the script mkerr.pl. Any changes
 * made after this point may be overwritten when the script is next run.
 */
static void ERR_load_DEADCAFE_strings(void);
static void ERR_unload_DEADCAFE_strings(void);
static void ERR_DEADCAFE_error(int function, int reason, char *file, int line);
#define DEADCAFEerr(f,r) ERR_DEADCAFE_error((f),(r),__FILE__,__LINE__)

/* Error codes for the DEADCAFE functions. */

/* Function codes. */
#define DEADCAFE_F_E_DEADCAFE_CTRL			 100

/* Reason codes. */
#define DEADCAFE_R_CTRL_COMMAND_NOT_IMPLEMENTED		 100

#ifdef  __cplusplus
}
#endif
#endif	/* !_DEADCAFE_ERR_H_ */
